// Configuration (centralized constants)

// Re-export types for convenience
export type {
  Account,
  AccountState,
  // Account types
  AccountType,
  AuditHookConfig,
  BundlerClient,
  BundlerClientConfig,
  Call,
  ChainId,
  ECDSAValidatorConfig,
  // Paymaster types
  ExtendedPaymasterData,
  FieldValidation,
  GasEstimate,
  GasPaymentConfig,
  GasPaymentType,
  InstalledModule,
  KeyringType,
  ModuleABI,
  ModuleConfigField,
  ModuleConfigSchema,
  ModuleInstallRequest,
  ModuleMetadata,
  ModuleStatus,
  // Module types
  ModuleType,
  ModuleUninstallRequest,
  MultiModeTransactionRequest,
  MultiSigValidatorConfig,
  // Network types
  Network,
  NetworkCurrency,
  NetworkState,
  PackedUserOperation,
  PartialUserOperation,
  PaymasterClient,
  PaymasterClientConfig,
  PaymasterData,
  PaymasterStubData,
  RecurringPaymentConfig,
  SessionKeyConfig,
  SmartAccount,
  SmartAccountClientConfig,
  SolidityType,
  SpendingLimitHookConfig,
  SponsorPolicy,
  SupportedToken,
  // Transaction types
  TransactionMode,
  TransactionResult,
  UserOperation,
  UserOperationGasEstimation,
  UserOperationReceipt,
  Validator,
  WebAuthnValidatorConfig,
} from '@stablenet/sdk-types'
export {
  // Account constants
  ACCOUNT_TYPE,
  CALL_TYPE,
  // Network constants
  CHAIN_IDS,
  canInstallModules,
  DEFAULT_CURRENCIES,
  ECDSA_VALIDATOR_ADDRESS,
  ENTRY_POINT_ADDRESS,
  ENTRY_POINT_V07_ADDRESS,
  EXEC_MODE,
  GAS_PAYMENT_TYPE,
  // Account utilities
  getAvailableTransactionModes,
  getDefaultCurrency,
  getDefaultTransactionMode,
  getModuleTypeName,
  isEIP7702Mode,
  // Transaction type guards
  isEOAMode,
  isERC20Gas,
  isExecutor,
  isFallback,
  isHook,
  isPolicy,
  isSigner,
  isSmartAccountMode,
  isSponsoredGas,
  // Module type guards
  isValidator,
  KERNEL_ADDRESSES,
  KERNEL_V3_1_FACTORY_ADDRESS,
  KEYRING_TYPE,
  MODULE_STATUS,
  MODULE_TYPE,
  // Module constants
  MODULE_TYPE_NAMES,
  // Paymaster constants
  PAYMASTER_RPC_METHODS,
  supportsSmartAccount,
  // Transaction constants
  TRANSACTION_MODE,
  // Note: BUNDLER_ERROR_CODES is exported from ./errors with extended SDK error codes
} from '@stablenet/sdk-types'
// Contract ABIs
export {
  // Validators (ERC-7579 Module Type 1)
  ECDSA_VALIDATOR_ABI,
  // ERC-4337 Entry Point
  ENTRY_POINT_ABI,
  // Stealth Addresses (EIP-5564 & EIP-6538)
  ERC5564_ANNOUNCER_ABI,
  ERC6538_REGISTRY_ABI,
  HEALTH_FACTOR_HOOK_ABI,
  // Kernel Smart Account & Factory
  KERNEL_ABI,
  KERNEL_FACTORY_ABI,
  LENDING_EXECUTOR_ABI,
  // DeFi Infrastructure
  MERCHANT_REGISTRY_ABI,
  // ERC-7579 Module Interface
  MODULE_INTERFACE_ABI,
  MULTISIG_VALIDATOR_ABI,
  // Executors (ERC-7579 Module Type 2)
  SESSION_KEY_EXECUTOR_ABI,
  // Hooks (ERC-7579 Module Type 4)
  SPENDING_LIMIT_HOOK_ABI,
  STAKING_EXECUTOR_ABI,
  SWAP_EXECUTOR_ABI,
  WEBAUTHN_VALIDATOR_ABI,
} from './abis'
// Clients
export { createBundlerClient } from './clients/bundlerClient'
// Indexer Client
export {
  createIndexerClient,
  formatTokenBalance,
  type GasStats,
  type IndexedTransaction,
  IndexerClient,
  type IndexerClientConfig,
  type PaginatedResult,
  parseTokenAmount,
  type TokenBalance,
  type TokenTransfer,
} from './clients/indexerClient'
export {
  createSmartAccountClient,
  type SendTransactionArgs,
  type SendUserOperationArgs,
  type SmartAccountClientActions,
} from './clients/smartAccountClient'
export {
  BASE_TRANSFER_GAS,
  CLIENT_CONFIG,
  DEFAULT_CALL_GAS_LIMIT,
  DEFAULT_CONFIRMATION_TIMEOUT,
  DEFAULT_CONFIRMATIONS,
  DEFAULT_MAX_RETRIES,
  DEFAULT_POLLING_INTERVAL,
  DEFAULT_PRE_VERIFICATION_GAS,
  DEFAULT_PROVIDER_TIMEOUT,
  DEFAULT_RETRY_DELAY,
  // Client configuration
  DEFAULT_RPC_TIMEOUT,
  DEFAULT_VERIFICATION_GAS_LIMIT,
  EIP7702_AUTH_GAS,
  GAS_BUFFER_DIVISOR,
  GAS_BUFFER_MULTIPLIER,
  GAS_CONFIG,
  GAS_PER_AUTHORIZATION,
  MAX_GAS_LIMIT,
  MAX_PRIORITY_FEE,
  // Gas configuration
  MIN_PRIORITY_FEE,
  PAYMASTER_POST_OP_GAS,
  PAYMASTER_VERIFICATION_GAS,
} from './config'
// EIP-7702 Module
export {
  // Types
  type Authorization,
  classifyAccountByCode,
  createAuthorization,
  // Functions
  createAuthorizationHash,
  createRevocationAuthorization,
  createSignedAuthorization,
  DELEGATE_PRESETS,
  DELEGATION_PREFIX,
  type DelegatePreset,
  type DelegationStatus,
  // Constants
  EIP7702_MAGIC,
  type EIP7702Result,
  extractDelegateAddress,
  formatAuthorization,
  getDelegatePresets,
  getDelegationStatus,
  isDelegatedAccount,
  isRevocationAuthorization,
  isValidAddress,
  parseSignature,
  SETCODE_TX_TYPE,
  type SetCodeTransactionParams,
  type SignedAuthorization,
  ZERO_ADDRESS,
} from './eip7702'
// Errors
export {
  assertCondition,
  assertDefined,
  BUNDLER_ERROR_CODES,
  BundlerError,
  type BundlerErrorCode,
  type BundlerErrorDetails,
  ConfigurationError,
  createBundlerError,
  createConfigurationError,
  createPaymasterError,
  createTransactionError,
  createUserOperationError,
  createValidationError,
  type ErrorContext,
  GasEstimationError,
  type GasEstimationErrorDetails,
  isBundlerError,
  isPaymasterError,
  // Utilities
  isSdkError,
  isTransactionError,
  isUserOperationError,
  normalizeError,
  PaymasterError,
  type PaymasterErrorDetails,
  // Types
  SDK_ERROR_CODES,
  // Classes
  SdkError,
  type SdkErrorCode,
  type SdkErrorDetails,
  TransactionError,
  type TransactionErrorDetails,
  UserOperationError,
  type UserOperationErrorDetails,
  ValidationError,
  withErrorHandling,
} from './errors'
// Gas Module
export {
  createEIP7702GasStrategy,
  createEOAGasStrategy,
  createGasEstimator,
  createGasStrategyRegistry,
  createSmartAccountGasStrategy,
  type ERC20GasEstimate,
  // Gas Estimation Strategies (OCP: extensible pattern)
  type GasEstimationStrategy,
  type GasEstimator,
  type GasEstimatorConfig,
  type GasPriceInfo,
  type GasPrices as GasStrategyPrices,
  type GasStrategyConfig,
  type GasStrategyRegistry,
} from './gas'
// Module System
export {
  type AuditLogEntry,
  BUILT_IN_MODULES,
  type ConflictCheckResult,
  // Nonce Utils
  type DecodedNonceKey,
  decodeValidatorNonceKey,
  type EncodeValidatorNonceKeyOptions,
  encodeValidatorNonceKey,
  isRootValidator,
  VALIDATION_MODE,
  type ValidationMode,
  VALIDATION_TYPE,
  type ValidationType,
  // Validator Router
  createValidatorRouter,
  type ValidatorRouter,
  type ValidatorRouterConfig,
  calculateRecurringPaymentStatus,
  calculateSelector,
  calculateSpendingLimitStatus,
  calculateTotalRecurringCost,
  checkSessionKeyPermission,
  createDAppSessionKey,
  // Module Client
  createModuleClient,
  createModuleOperationClient,
  // Sub-clients (SRP: separated concerns)
  createModuleQueryClient,
  createModuleRegistry,
  decodeAuditEventFlags,
  decodeECDSAValidatorInit,
  decodeMultiSigValidatorInit,
  decodeTokenReceiverFlags,
  decodeWebAuthnValidatorInit,
  // Built-in modules
  ECDSA_VALIDATOR,
  type ExecutorValidationResult,
  encodeAuditHookInit,
  encodeBatchExecutorCalls,
  encodeBatchFallbackRegistration,
  encodeECDSASignature,
  // Validator Utilities
  encodeECDSAValidatorInit,
  encodeERC721ReceivedReturn,
  encodeERC1155BatchReceivedReturn,
  encodeERC1155ReceivedReturn,
  encodeExecuteRecurringPayment,
  encodeExecutorCall,
  encodeFallbackHandlerRegistration,
  encodeFlashLoanInit,
  encodeMultipleSpendingLimitsInit,
  encodeMultiSigSignature,
  encodeMultiSigValidatorInit,
  encodeRecurringPaymentInit,
  // Executor Utilities
  encodeSessionKeyInit,
  encodeSetLimit,
  // Hook Utilities
  encodeSpendingLimitInit,
  encodeSupportsInterfaceCall,
  // Fallback Utilities
  encodeTokenReceiverInit,
  encodeWebAuthnSignature,
  encodeWebAuthnValidatorInit,
  executorUtils,
  type FallbackHandlerRegistration,
  type FallbackValidationResult,
  type FlashLoanCallbackConfig,
  fallbackUtils,
  formatAuditLogEntry,
  formatSpendingLimit,
  generatePaymentId,
  generateSignerChangeHash,
  getPeriodName,
  getSupportedInterfaceIds,
  getTokenReceiverHandlers,
  type HookValidationResult,
  hookUtils,
  INTERFACE_IDS,
  INTERFACE_SELECTORS,
  identifyValidatorType,
  isFlashLoanAuthorized,
  isValidSignatureFormat,
  type ModuleCalldata,
  type ModuleClient,
  type ModuleClientConfig,
  type ModuleInstallResult,
  type ModuleOperationClient,
  type ModuleOperationClientConfig,
  type ModuleQueryClient,
  type ModuleQueryClientConfig,
  type ModuleRegistry,
  type ModuleRegistryConfig,
  type ModuleRegistryEntry,
  type ModuleSearchFilters,
  MULTISIG_VALIDATOR,
  PERIOD_PRESETS,
  type PermissionCheckResult,
  parseWebAuthnCredential,
  RECURRING_PAYMENT_EXECUTOR,
  type RecurringPaymentStatus,
  SESSION_KEY_EXECUTOR,
  SPENDING_LIMIT_HOOK,
  type SpendingLimitStatus,
  suggestSpendingLimit,
  TOKEN_RECEIVER_FALLBACK,
  type TokenReceiverCapability,
  type ValidationResult,
  type ValidatorValidationResult,
  validateAuditHookConfig,
  validateECDSAValidatorConfig,
  validateFlashLoanConfig,
  validateMultiSigValidatorConfig,
  validateRecurringPaymentConfig,
  validateSessionKeyConfig,
  validateSpendingLimitConfig,
  validateTokenReceiverConfig,
  validateWebAuthnValidatorConfig,
  validatorUtils,
  WEBAUTHN_VALIDATOR,
  type WebAuthnSignatureData,
  wouldExceedLimit,
} from './modules'

// Paymaster Client
export {
  createPaymasterClient,
  type ERC20PaymentEstimate,
  type PartialUserOperationForPaymaster,
  type PaymasterClientInstance,
  type PaymasterResponse,
} from './paymasterClient'
// Providers Module (DIP: Abstraction layer for blockchain RPC)
export {
  type BlockData,
  createViemProvider,
  type EstimateGasParams,
  type GasPrices,
  type ReadContractParams,
  type RpcProvider,
  type RpcProviderConfig,
  type ViemProvider,
  type WaitForReceiptOptions,
} from './providers'
// RPC Module
export {
  BUNDLER_ERROR_CODES as BUNDLER_RPC_ERROR_CODES,
  createBundlerRpcClient,
  // Client
  createJsonRpcClient,
  createPaymasterRpcClient,
  getErrorDescription,
  isBundlerError as isBundlerRpcError,
  isJsonRpcError,
  isPaymasterError as isPaymasterRpcError,
  isRpcError,
  isStandardRpcError,
  // Error codes
  JSON_RPC_ERROR_CODES,
  type JsonRpcClient,
  // Types
  type JsonRpcClientConfig,
  type JsonRpcError,
  type JsonRpcRequest,
  type JsonRpcRequestOptions,
  type JsonRpcResponse,
  PAYMASTER_ERROR_CODES,
  // Error utilities
  RpcError,
} from './rpc'
// Security Module
export {
  type ApiWarning,
  type AuthorizationRiskLevel,
  type AuthorizationRiskParams,
  type AuthorizationRiskResult,
  // Authorization Risk Analyzer (EIP-7702)
  analyzeAuthorizationRisk,
  type ContractInteraction,
  createConsoleDeprecationNotice,
  createInputValidator,
  createPhishingDetector,
  createRateLimiter,
  createSignatureRiskAnalyzer,
  createTransactionRiskAnalyzer,
  createTypedDataValidator,
  DEFAULT_LIMITS,
  type DecodedMethod,
  // Legacy API Warning
  DeprecationStatus,
  type DeprecationStatusType,
  type DomainResult,
  type DomainValidationResult,
  type DomainWarning,
  type DomainWarningType,
  type EIP712TypedData,
  type EthSignSettings,
  formatApiWarningForUI,
  formatRiskWarningsForUI,
  getAllApiWarnings,
  getApiWarning,
  getAuthorizationSummary,
  getEthSignSettings,
  getWarningsByStatus,
  type HexValidationOptions,
  hasApiWarning,
  type InputValidationResult,
  // Input Validator
  InputValidator,
  isEthSignAllowed,
  isValidChainId,
  isValidHex,
  isValidInputAddress,
  isValidRpcRequest,
  isValidTransactionObject,
  METHOD_CATEGORIES,
  // Phishing Detector
  PhishingDetector,
  type PhishingDetectorConfig,
  PhishingPatternType,
  type PhishingPatternTypeValue,
  type PhishingResult,
  type RateLimitConfig,
  // Rate Limiter
  RateLimiter,
  type RateLimitResult,
  RiskLevel,
  type RiskLevelType,
  type RpcRequestObject,
  resetEthSignSettings,
  type SanitizeOptions,
  SignatureMethod,
  type SignatureMethodType,
  // Signature Risk Analyzer
  SignatureRiskAnalyzer,
  SignatureRiskLevel,
  type SignatureRiskLevelType,
  type SignatureRiskResult,
  SignatureRiskType,
  type SignatureRiskTypeValue,
  sanitizeString,
  shouldBlockMethod,
  shouldShowEthSignWarning,
  type TransactionObject,
  // Transaction Risk Analyzer
  TransactionRiskAnalyzer,
  TransactionRiskLevel,
  type TransactionRiskLevelType,
  type TransactionRiskParams,
  type TransactionRiskResult,
  TransactionRiskType,
  type TransactionRiskTypeValue,
  type TypedData,
  type TypedDataDomain,
  // Typed Data Validator (EIP-712)
  TypedDataValidator,
  updateEthSignSettings,
} from './security'
// Transaction Module
export {
  type AuthorizationSigner,
  type BaseStrategyConfig,
  type BuiltEIP7702Transaction,
  type BuiltEOATransaction,
  type CombinedSigner,
  createEIP7702Strategy,
  // EIP-7702
  createEIP7702TransactionBuilder,
  createEOAStrategy,
  createEOATransactionBuilder,
  createSmartAccountStrategy,
  createStrategyRegistry,
  // Router
  createTransactionRouter,
  type DelegationRequest,
  type EIP7702TransactionBuilder,
  type EIP7702TransactionConfig,
  type EOATransactionBuilder,
  type EOATransactionConfig,
  type ExecuteOptions,
  type PreparedTransaction,
  type SmartAccountStrategyConfig,
  type StrategyExecuteOptions,
  type StrategyPreparedTransaction,
  type StrategyRegistry,
  type TransactionRouter,
  type TransactionRouterConfig,
  type TransactionSigner,
  // Strategies (for advanced usage)
  type TransactionStrategy,
} from './transaction'
// Paymaster Codec & Hasher
export {
  PAYMASTER_DATA_VERSION,
  HEADER_SIZE,
  PaymasterType,
  encodePaymasterData,
  decodePaymasterData,
  isPaymasterDataSupported,
  envelopeLength,
  encodePaymasterDataWithSignature,
  splitEnvelopeAndSignature,
  computePaymasterDomainSeparator,
  computeUserOpCoreHash,
  computePaymasterHash,
  PAYMASTER_DOMAIN_NAME,
  PAYMASTER_DOMAIN_VERSION,
  encodeVerifyingPayload,
  decodeVerifyingPayload,
  encodeSponsorPayload,
  decodeSponsorPayload,
  encodeErc20Payload,
  decodeErc20Payload,
  encodePermit2Payload,
  decodePermit2Payload,
  type PaymasterDataEnvelope,
  type VerifyingPayloadData,
  type SponsorPayloadData,
  type Erc20PayloadData,
  type Permit2PayloadData,
} from './paymaster'
// Utils
export {
  buildUserOpTypedData,
  computeDomainSeparator,
  getUserOperationHash,
  packUserOperation,
  signUserOpForKernel,
  unpackUserOperation,
} from './utils/userOperation'
export {
  SIG_VALIDATION_FAILED,
  VALIDITY_BLOCK_RANGE_FLAG,
  VALIDITY_BLOCK_RANGE_MASK,
  isSignatureValidationFailed,
  packValidationData,
  parseValidationData,
  usesBlockNumberMode,
  type ValidationData,
} from './utils/validationData'
