#!/usr/bin/env tsx
/**
 * Generate TypeScript address file from Foundry deployment output
 *
 * Usage:
 *   pnpm generate
 *   pnpm generate --chain 31337
 *   pnpm generate --input ../../poc-contract/deployments
 */

import { existsSync } from 'node:fs'
import { readFile, readdir, writeFile } from 'node:fs/promises'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

const ZERO_ADDRESS = '0x0000000000000000000000000000000000000000'

interface DeploymentOutput {
  [key: string]: string
}

interface ChainDeployment {
  chainId: number
  addresses: DeploymentOutput
}

async function findDeploymentFiles(basePath: string): Promise<string[]> {
  const files: string[] = []

  try {
    const entries = await readdir(basePath, { withFileTypes: true })

    for (const entry of entries) {
      const fullPath = join(basePath, entry.name)

      if (entry.isDirectory()) {
        // Check for addresses.json in chain directories (e.g., 31337/addresses.json)
        const addressFile = join(fullPath, 'addresses.json')
        if (existsSync(addressFile)) {
          files.push(addressFile)
        }

        // Also check broadcast directory format
        const broadcastDir = join(fullPath, 'broadcast')
        if (existsSync(broadcastDir)) {
          const subFiles = await findDeploymentFiles(broadcastDir)
          files.push(...subFiles)
        }
      } else if (entry.name === 'addresses.json') {
        files.push(fullPath)
      }
    }
  } catch {
    // Directory doesn't exist
  }

  return files
}

async function loadDeployment(filePath: string): Promise<ChainDeployment | null> {
  try {
    const content = await readFile(filePath, 'utf-8')
    const data = JSON.parse(content)

    // Extract chain ID from path or file content
    let chainId: number

    if (data.chainId) {
      chainId = data.chainId
    } else {
      // Try to extract from path (e.g., /deployments/31337/addresses.json)
      const pathMatch = filePath.match(/\/(\d+)\//)
      if (pathMatch) {
        chainId = Number.parseInt(pathMatch[1], 10)
      } else {
        console.warn(`Could not determine chain ID for ${filePath}`)
        return null
      }
    }

    return {
      chainId,
      addresses: data,
    }
  } catch (error) {
    console.warn(`Failed to load ${filePath}:`, error)
    return null
  }
}

function generateAddressesTs(deployments: ChainDeployment[]): string {
  const lines: string[] = [
    '/**',
    ' * Auto-generated contract addresses',
    ' * DO NOT EDIT - This file is generated by scripts/generate-addresses.ts',
    ' *',
    ` * Generated: ${new Date().toISOString()}`,
    ' * To regenerate: pnpm generate',
    ' */',
    '',
    "import type { ChainAddresses } from '../types'",
    '',
    `const ZERO_ADDRESS = '${ZERO_ADDRESS}' as const`,
    '',
    '/**',
    ' * Contract addresses by chain ID',
    ' */',
    'export const CHAIN_ADDRESSES: Record<number, ChainAddresses> = {',
  ]

  for (const deployment of deployments) {
    const { chainId, addresses } = deployment
    const chainName = getChainName(chainId)

    lines.push(`  // ${chainName}`)
    lines.push(`  ${chainId}: {`)
    lines.push(`    chainId: ${chainId},`)
    lines.push('    core: {')
    lines.push(
      `      entryPoint: '${addresses.entryPoint || addresses.EntryPoint || ZERO_ADDRESS}',`
    )
    lines.push(`      kernel: '${addresses.kernel || addresses.Kernel || ZERO_ADDRESS}',`)
    lines.push(
      `      kernelFactory: '${addresses.kernelFactory || addresses.KernelFactory || addresses.accountFactory || ZERO_ADDRESS}',`
    )
    lines.push('    },')
    lines.push('    validators: {')
    lines.push(
      `      ecdsaValidator: '${addresses.ecdsaValidator || addresses.ECDSAValidator || ZERO_ADDRESS}',`
    )
    lines.push(
      `      webAuthnValidator: '${addresses.webAuthnValidator || addresses.WebAuthnValidator || ZERO_ADDRESS}',`
    )
    lines.push(
      `      multiEcdsaValidator: '${addresses.multiEcdsaValidator || addresses.MultiECDSAValidator || ZERO_ADDRESS}',`
    )
    lines.push('    },')
    lines.push('    executors: {')
    lines.push(
      `      ownableExecutor: '${addresses.ownableExecutor || addresses.OwnableExecutor || ZERO_ADDRESS}',`
    )
    lines.push('    },')
    lines.push('    hooks: {')
    lines.push(
      `      spendingLimitHook: '${addresses.spendingLimitHook || addresses.SpendingLimitHook || ZERO_ADDRESS}',`
    )
    lines.push('    },')
    lines.push('    paymasters: {')
    lines.push(
      `      verifyingPaymaster: '${addresses.verifyingPaymaster || addresses.VerifyingPaymaster || addresses.paymaster || ZERO_ADDRESS}',`
    )
    lines.push(
      `      tokenPaymaster: '${addresses.tokenPaymaster || addresses.TokenPaymaster || ZERO_ADDRESS}',`
    )
    lines.push('    },')
    lines.push('    privacy: {')
    lines.push(
      `      stealthAnnouncer: '${addresses.stealthAnnouncer || addresses.StealthAnnouncer || ZERO_ADDRESS}',`
    )
    lines.push(
      `      stealthRegistry: '${addresses.stealthRegistry || addresses.StealthRegistry || ZERO_ADDRESS}',`
    )
    lines.push('    },')
    lines.push('    compliance: {')
    lines.push(
      `      kycRegistry: '${addresses.kycRegistry || addresses.KYCRegistry || ZERO_ADDRESS}',`
    )
    lines.push(
      `      complianceValidator: '${addresses.complianceValidator || addresses.ComplianceValidator || ZERO_ADDRESS}',`
    )
    lines.push('    },')
    lines.push('    subscriptions: {')
    lines.push(
      `      subscriptionManager: '${addresses.subscriptionManager || addresses.SubscriptionManager || ZERO_ADDRESS}',`
    )
    lines.push(
      `      recurringPaymentExecutor: '${addresses.recurringPaymentExecutor || addresses.RecurringPaymentExecutor || ZERO_ADDRESS}',`
    )
    lines.push(
      `      permissionManager: '${addresses.erc7715PermissionManager || addresses.ERC7715PermissionManager || addresses.permissionManager || ZERO_ADDRESS}',`
    )
    lines.push('    },')
    lines.push('    delegatePresets: [')

    // Add delegate preset if Kernel is available
    const kernelAddress = addresses.kernel || addresses.Kernel
    if (kernelAddress && kernelAddress !== ZERO_ADDRESS) {
      lines.push('      {')
      lines.push("        name: 'Kernel v3.0',")
      lines.push("        description: 'ZeroDev Kernel - ERC-7579 compatible Smart Account',")
      lines.push(`        address: '${kernelAddress}',`)
      lines.push("        features: ['ERC-7579', 'Modular', 'Gas Sponsorship', 'Session Keys'],")
      lines.push('      },')
    }

    lines.push('    ],')
    lines.push('  },')
    lines.push('')
  }

  lines.push('}')
  lines.push('')

  // Add service URLs
  lines.push('/**')
  lines.push(' * Service URLs by chain ID')
  lines.push(' */')
  lines.push(
    'export const SERVICE_URLS: Record<number, { bundler: string; paymaster: string; stealthServer: string }> = {'
  )

  for (const deployment of deployments) {
    const { chainId } = deployment
    const urls = getServiceUrls(chainId)
    lines.push(`  ${chainId}: {`)
    lines.push(`    bundler: '${urls.bundler}',`)
    lines.push(`    paymaster: '${urls.paymaster}',`)
    lines.push(`    stealthServer: '${urls.stealthServer}',`)
    lines.push('  },')
  }

  lines.push('}')
  lines.push('')

  // Add default tokens
  lines.push('/**')
  lines.push(' * Default tokens by chain ID')
  lines.push(' */')
  lines.push(
    'export const DEFAULT_TOKENS: Record<number, Array<{ address: `0x${string}`; name: string; symbol: string; decimals: number; logoUrl?: string }>> = {'
  )

  for (const deployment of deployments) {
    const { chainId, addresses } = deployment
    const tokens = getDefaultTokens(chainId, addresses)
    lines.push(`  ${chainId}: [`)
    for (const token of tokens) {
      lines.push('    {')
      lines.push(`      address: '${token.address}',`)
      lines.push(`      name: '${token.name}',`)
      lines.push(`      symbol: '${token.symbol}',`)
      lines.push(`      decimals: ${token.decimals},`)
      lines.push('    },')
    }
    lines.push('  ],')
  }

  lines.push('}')
  lines.push('')

  return lines.join('\n')
}

function getChainName(chainId: number): string {
  const names: Record<number, string> = {
    1: 'Mainnet',
    11155111: 'Sepolia Testnet',
    31337: 'Devnet (Anvil)',
  }
  return names[chainId] || `Chain ${chainId}`
}

function getServiceUrls(chainId: number): {
  bundler: string
  paymaster: string
  stealthServer: string
} {
  const urls: Record<number, { bundler: string; paymaster: string; stealthServer: string }> = {
    31337: {
      bundler: 'http://localhost:4337',
      paymaster: 'http://localhost:4338',
      stealthServer: 'http://localhost:4339',
    },
    11155111: {
      bundler: 'https://testnet.stablenet.io/bundler',
      paymaster: 'https://testnet.stablenet.io/paymaster',
      stealthServer: 'https://testnet.stablenet.io/stealth',
    },
    1: {
      bundler: 'https://stablenet.io/bundler',
      paymaster: 'https://stablenet.io/paymaster',
      stealthServer: 'https://stablenet.io/stealth',
    },
  }
  return urls[chainId] || urls[31337]
}

function getDefaultTokens(
  chainId: number,
  addresses: DeploymentOutput
): Array<{ address: string; name: string; symbol: string; decimals: number }> {
  const baseTokens = [
    {
      address: ZERO_ADDRESS,
      name: 'Ether',
      symbol: 'ETH',
      decimals: 18,
    },
  ]

  if (chainId === 31337) {
    // Add test tokens for devnet
    if (addresses.usdc || addresses.USDC) {
      baseTokens.push({
        address: addresses.usdc || addresses.USDC,
        name: 'USD Coin',
        symbol: 'USDC',
        decimals: 6,
      })
    } else {
      // Default devnet USDC address
      baseTokens.push({
        address: '0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9',
        name: 'USD Coin',
        symbol: 'USDC',
        decimals: 6,
      })
    }

    if (addresses.dai || addresses.DAI) {
      baseTokens.push({
        address: addresses.dai || addresses.DAI,
        name: 'Dai Stablecoin',
        symbol: 'DAI',
        decimals: 18,
      })
    } else {
      baseTokens.push({
        address: '0x5FC8d32690cc91D4c39d9d3abcBD16989F875707',
        name: 'Dai Stablecoin',
        symbol: 'DAI',
        decimals: 18,
      })
    }
  }

  return baseTokens
}

async function main() {
  const args = process.argv.slice(2)

  // Parse arguments
  let inputPath = resolve(__dirname, '../../../../poc-contract/deployments')
  let specificChain: number | null = null

  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--input' && args[i + 1]) {
      inputPath = resolve(args[i + 1])
      i++
    } else if (args[i] === '--chain' && args[i + 1]) {
      specificChain = Number.parseInt(args[i + 1], 10)
      i++
    }
  }

  console.log(`Looking for deployments in: ${inputPath}`)

  // Find deployment files
  const files = await findDeploymentFiles(inputPath)

  if (files.length === 0) {
    console.log('No deployment files found. Using default addresses.')
    return
  }

  console.log(`Found ${files.length} deployment file(s)`)

  // Load deployments
  const deployments: ChainDeployment[] = []

  for (const file of files) {
    const deployment = await loadDeployment(file)
    if (deployment) {
      if (specificChain === null || deployment.chainId === specificChain) {
        deployments.push(deployment)
        console.log(`  Loaded chain ${deployment.chainId} from ${file}`)
      }
    }
  }

  if (deployments.length === 0) {
    console.log('No valid deployments loaded.')
    return
  }

  // Generate TypeScript file
  const content = generateAddressesTs(deployments)
  const outputPath = resolve(__dirname, '../src/generated/addresses.ts')

  await writeFile(outputPath, content, 'utf-8')
  console.log(`\nGenerated: ${outputPath}`)
  console.log(`Chains: ${deployments.map((d) => d.chainId).join(', ')}`)
}

main().catch(console.error)
