export { Home } from './Home'
export { Send } from './Send'
export { Receive } from './Receive'
export { Activity } from './Activity'
export { Settings } from './Settings'
export { Lock } from './Lock'
export { Bank } from './Bank'
export { BuyPage } from './BuyPage'
